### ISSUE TITLE
Game freezes after a while

### ISSUE THREAD

**Issue by therealmadprofessor** [Innoxia/liliths-throne-public#1081]
I know you had fixed this bug a while back, but it's cropped back up again. After about five minutes, the game becomes unresponsive after trying to move to another area or save/load. Gameplay itself is pretty choppy this release, generally speaking, in terms of moving about, dialogue popping up, etc

**Comment by Twand37** [comment]
I believe this is the same bug that keeps breaking the game for me.
[error.log](https://github.com/Innoxia/liliths-throne-public/files/2916580/error.log)
This is my most recent save, in which the error consistently happens on first area transition:
[Save.zip](https://github.com/Innoxia/liliths-throne-public/files/2916596/Save.zip)

**Comment by Innoxia** [comment]
Thank you for the error log and save! That bug is fixed in the upcoming v0.3.1.1 hotfix (out later tonight), so if you're still running into this issue after that's released, then please let me know here and I'll reopen this issue.

**Comment by therealmadprofessor** [comment]
Hello again, I'm still having the same problems even with the hotfix version. Even encountering random clothing and such can cause the game to be unresponsive when trying to click out and go back. I remember the similar problem was fixed in this patch

v0.2.12.95 patch notes
Bugs:
    Fixed major bug where entering a lot of areas would freeze the game.

**Comment by therealmadprofessor** [comment]
I've noticed that when I press M to bring up the map, I can see the area where I wanted to go or the tile I was supposed to be on. It isn't showing on the minimap otherwise.

**Comment by Innoxia** [comment]
Thank you for the report - would it be possible to get your error.log file?

**Comment by therealmadprofessor** [comment]
Sure thing
[error.log](https://github.com/Innoxia/liliths-throne-public/files/2922493/error.log)

**Comment by Innoxia** [comment]
It looks like you're getting an out of memory error - I assume that your save file is quite large (50MB+)?

I will try to optimise the loading for the next version, but until then, you could try running the .jar from the command line and giving it more memory to work with (https://superuser.com/questions/269701/how-do-i-allocate-more-ram-to-java).

**Comment by therealmadprofessor** [comment]
Actually, my save file is around 18MB. I've added it here if you want to take a look.
[New Save1.zip](https://github.com/Innoxia/liliths-throne-public/files/2922548/New.Save1.zip)

**Comment by Innoxia** [comment]
Thank you, I will take a look at the save and fix and other bugs that I find thanks to it. ^^

**Comment by therealmadprofessor** [comment]
Great, thanks for all your hard work.
